spring.application.name=api

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shortify
spring.datasource.username=postgres
spring.datasource.password=27485335

# Estratégia de atualização do banco (Cria as tabelas automaticamente pelas classes Java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true